project_id              = "qwiklabs-gcp-03-07603a1adba2"
region                  = "us-central1"
cloudrun_instance_name  = "book-shelf-app"
vpc_name                = "usc1-vpc"
subnet_name             = "usc1-subnet"
subnet_ip_ranges        = "10.10.0.0/24"
service_acc             = "test-sa@qwiklabs-gcp-03-07603a1adba2.iam.gserviceaccount.com"
